[package]
name = "new3_3"
version = "0.1.0"
authors = ["Daiki Tomioka <chocolate0785lego@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
